### PR TITLE
Fixes #9: Intercept «incompatible type in overriding» errors

### LINKED ISSUE #9: Intercept «incompatible type in overriding» errors
Example:
```scala
trait Base {
  type Env
  def makeEnv: ZLayer[Any, Nothing, Env]
}

object ZMain extends Base {
  override type Env = String

  override def makeEnv: ZLayer[Any with Long, Nothing, String] = ZLayer.succeed("42")
}
```

Output:
```
billing/billing/billing-tms/app/src/ZMain.scala:34: error: incompatible type in overriding
def makeEnv: zio.ZLayer[Any,Nothing,ru.yandex.vertis.billing.tms.ZMain0.Env] (defined in trait Base);
 found   : zio.ZLayer[Any with Long,Nothing,String]
 required: zio.ZLayer[Any,Nothing,ru.yandex.vertis.billing.tms.ZMain0.Env]
    (which expands to)  zio.ZLayer[Any,Nothing,String]
  override def makeEnv: ZLayer[Any with Long, Nothing, String] = ZLayer.succeed("42")
               ^
zio.ZLayer[Any with Long,Nothing,String] <: zio.ZLayer[Any,Nothing,ru.yandex.vertis.billing.tms.ZMain0.Env]?
```

Looks like magic regex ignores such errors because it is `incompatible type in overriding`, not a `type mismatch` 🤔

### PR DESCRIPTION
**Pull request by poslegm**
Test case:
```scala
import zio._
trait Base {
  type Env
  def makeEnv: ZLayer[Any, Nothing, Env]
}

object ZMain extends Base {
  override type Env = String

  override def makeEnv: ZLayer[Any with Long, Long, "42"] = ZLayer.succeed("42")
}
```

Output:
```
[error] /private/tmp/clippy-test/src/main/scala/Main.scala:10:16:
[error]   ZIO Type Mismatch
[error]
[error] Your effect requires the following environment in overriding, but it was not presented in original type:
[error]
[error] ❯ Long
[error]
[error] Your effect has an error type mismatch in overriding:
[error]
[error] ❯ Required: Nothing
[error] ❯ Found   : Long
[error]
[error] Your effect has a return type mismatch:
[error]
[error] ❯ Required: String
[error] ❯ Found   : "42"
[error]
[error]   override def makeEnv: ZLayer[Any with Long, Long, "42"] = ZLayer.succeed("42")
[error]                ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed Jul 1, 2023, 4:30:08 PM
```

Test case:
```scala
import zio._

object ZMainSimple {
   def makeEnv: ZLayer[Any, Throwable, Long] = ZLayer.service[Int] >>> ZLayer.succeed("asd")
}
```

Output:
```
[error] /private/tmp/clippy-test/src/main/scala/TestSimple.scala:4:68:
[error]   ZIO Type Mismatch
[error]
[error] Your effect requires the following environment, but it was not provided:
[error]
[error] ❯ Int
[error]
[error] Your effect has an error type mismatch:
[error]
[error] ❯ Required: Throwable
[error] ❯ Found   : Nothing
[error]
[error] Your effect has a return type mismatch:
[error]
[error] ❯ Required: Long
[error] ❯ Found   : String
[error]
[error]    def makeEnv: ZLayer[Any, Throwable, Long] = ZLayer.service[Int] >>> ZLayer.succeed("asd")
[error]                                                                    ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed Jul 1, 2023, 4:30:03 PM
```

### CODE REVIEW

**Review by hmemcpy — APPROVED** [review]
This is amazing. Thanks a lot!

**Comment by hmemcpy** [comment]
I'll cut a new release soon! Thanks!

**Comment by poslegm** [comment]
> I'll cut a new release soon! Thanks!

Kindly reminder ;)

**Comment by hmemcpy** [comment]
Sorry for the delay, just pushed it to bake ;)
Should be ready soon. Thanks again for your contribution!

**Comment by poslegm** [comment]
Thank you!

**Pull request merged**
